### ISSUE TITLE
Add paredit or parinfer keybindings

### ISSUE THREAD

**Issue by fiddlerwoaroof** [tamamu/darkmatter#14]
We should add paredit keybindings or incorporate parinfer.  It would make editing lisp in the browser much nicer.

I have some vim (evil-mode) keybindings that I find really nice for paredit in my emacs configuration: https://github.com/fiddlerwoaroof/dotfiles/blob/master/emacs.d/emacs#L220

**Comment by tamamu** [comment]
That's cool. There is not Parinfer plugin for Ace editor, so let's go with Paredit.
I'm going to embed [Paredit.js](http://robert.kra.hn/projects/paredit-js) to the editor.

**Comment by fiddlerwoaroof** [comment]
Great

**Comment by tamamu** [comment]
close
