### ISSUE TITLE
404 when opening a lisp file

### ISSUE THREAD

**Issue by vindarel** [tamamu/darkmatter#17]
Hello,
When I open a directory the UI shows me the lisp of available files correctly, but on clicking one of them I get a 404 Not Found error :( No information is printed in the console.

Any idea ? (to at least give you debug information)

thanks !

**Comment by tamamu** [comment]
Hi, @vindarel 
Darkmatter supports only a format for Darkmatter(.dm.lisp) that is made by Darkmatter, the plain lisp source code is not supported for beta version. I 'm planning to support only the format of Jupyter Notebook 
 for next version, but don't worry, I'll make a converter from the current to that of Jupyter Notebook.

For now, you can create a new Darkmatter file.

Sorry for the confusion.

**Comment by vindarel** [comment]
aaallright. I didn't get it, nor with the readme nor with the interface but that makes totally sense since is a notebook after all…

It is really cool then !

ps: is there some sort of completion system ?
