### ISSUE TITLE
installation on macOS

### ISSUE THREAD

**Issue by t-cool** [tamamu/darkmatter#18]
It seems we need to install trivial-mimes in advance:
$ ros install Shinmera/trivial-mimes

******************************************************
[package darkmatter].[1/3] System 'darkmatter' found. Loading the system..Aborted during step [1/3].
Unhandled ASDF/FIND-COMPONENT:MISSING-COMPONENT in thread #<SB-THREAD:THREAD "main thread" RUNNING
                                                             {1001958083}>:
  Component "trivial-mimes" not found

Backtrace for: #<SB-THREAD:THREAD "main thread" RUNNING {1001958083}>
0: (SB-DEBUG::DEBUGGER-DISABLED-HOOK Component "trivial-mimes" not found #<unused argument> :QUIT T)

**Comment by analyticd** [comment]
I found this to be true as well. Perhaps this could be added to the readme and then this closed @tamamu ? Thanks for this great project. Appreciate it.
